import turtle
xp = -400 ###bylo 400
yp = 350  #### bylo 350
def name(xp,yp):
    t = turtle.Turtle()
    s = turtle.Screen()
    ###
    t.pensize(2)
    t.speed(2)
    s.bgcolor("black")
    t.pencolor("blue")
    t.penup()
    t.speed(200)
    t.setpos(xp,yp)
    t.pendown()
    t.forward(50)
    t.circle(-15,180)
    t.forward(15)
    t.penup()
    t.goto(xp+30,yp)
    t.left(90)
    t.pendown()
    t.forward(50)
    t.penup()
    t.setpos(xp+50,yp-50)
    t.pendown()
    t.right(180)
    t.forward(15)
    t.penup()
    t.goto(xp+70,yp-50)
    t.pendown()
    t.right(90)
    t.circle(7,360)
    t.penup()
    t.goto(xp+90,yp-50)
    t.left(90)
    t.pendown()
    t.forward(50)
    t.penup()
    t.goto(xp+80,yp-25)
    t.right(90)
    t.pendown()
    t.forward(20)
    t.penup()
    t.goto(xp+105,yp-50)
    t.left(90)
    t.pendown()
    t.forward(15)
    t.goto(xp+105,yp-40)
    t.circle(-5,90)
    t.forward(5)
    t.penup()
    t.goto(100,100)
    turtle.done()
name(-400,350)